{"name": "Проверка ошибки при авторизации с неверным логином или паролем", "status": "passed", "parameters": [{"name": "field", "value": "'login'"}], "start": 1701623483353, "stop": 1701623483434, "uuid": "6872a485-d6d7-4b97-9009-7dfc03cd1c49", "historyId": "6f03d551bed0deb02b29f981193e1d2e", "testCaseId": "4db5d0b446ab9c4f6b27d7c467c0f18e", "fullName": "tests.test_login#test_login_courier_with_invalid_log_or_pass", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login"}, {"name": "host", "value": "B-F2027P7V-0432.local"}, {"name": "thread", "value": "82330-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login"}]}