{"name": "Проверка ошибки при авторизации под несуществующим пользователем", "status": "passed", "start": 1701623543947, "stop": 1701623544009, "uuid": "4b974dae-a36c-4575-b986-8d69836367a5", "historyId": "172973e359714cc626ec8e99b8917fd5", "testCaseId": "172973e359714cc626ec8e99b8917fd5", "fullName": "tests.test_login#test_login_unregistered_courier", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login"}, {"name": "host", "value": "B-F2027P7V-0432.local"}, {"name": "thread", "value": "82330-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login"}]}